---  
- name: install tomcat 10
  hosts: all 
  become: yes 
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        state: present
        update_cache: true
   